languageCode: "en-us"
title: "lytedev"
baseURL: "https://lyte.dev/"
theme: "lytedev"
metaDataFormat: "yaml"
pygmentsCodeFences: true
pygmentsCodeFencesGuessSyntax: true
pygmentsUseClasses: true

permalinks:
  post: /blog/:title

menu:
  main:
    - Name: "Blog"
      Pre: ""
      Weight: -100
      Identifier: "blog"
      URL: "/blog"
    - Name: "Contact"
      Pre: ""
      Weight: -100
      Identifier: "contact"
      URL: "/contact"
    - Name: "About"
      Pre: ""
      Weight: -100
      Identifier: "about"
      URL: "/about"
    # - Name: "Blog"
    #   Pre: ""
    #   Weight: -110
    #   Identifier: "blog"
    #   URL: "/blog"

params:
  googleAnalyticsCode: "UA-43157826-1"
  themeColor: "#a02d3a" # #e03d5a
  index:
    image: /img/desktop-blurred.jpg
    heroBackgroundColor: "#333"
    imageOverlayColor: "#000"
    imageOverlayOpacity: "0.5"
    logoColor: "#e03d5a"

  author:
    name: "Daniel Flanagan"
    email: "daniel@lyte.dev"
