name = "lytedev"
license = "MIT"
licenselink = "//opensource.org/licenses/MIT"
description = "The theme for my personal site at https://lyte.dev"
homepage = "https://github.com/lytedev/lytedev-hugo-theme"
tags = ["blog", "portfolio", "hero"]
features = ["blog", "hero", "portfolio"]

[permalinks]
  blog = /blog/:year/:month/:day/:title

[author]
  name = "lytedev"
  homepage = "https://lyte.dev"
