// Generated by CoffeeScript 1.12.4
(function() {
  var animate, easeInOut, log;

  document.documentElement.classList.remove('no-js');

  log = function() {
    var args;
    if (typeof console === "undefined" || console === null) {
      return false;
    }
    args = [].slice.apply(arguments);
    return console.log.apply(console, args);
  };

  log('Thanks for checking out my site\'s theme\'s code!');

  log('The raw source is available on my GitHub at https://github.com/lytedev');

  easeInOut = function(t) {
    return (Math.sin((t + (Math.PI / 2)) * Math.PI) + 1) / 2;
  };

  animate = function(obj, key, endValue, duration, easeFunc) {
    var diff, elapsed, initialTime, initialVal, update;
    if (typeof requestAnimationFrame === "undefined" || requestAnimationFrame === null) {
      return obj[key] = endValue;
    }
    if (easeFunc == null) {
      easeFunc = function(time) {
        return time;
      };
    }
    initialVal = parseFloat(obj[key]);
    diff = parseFloat(endValue) - initialVal;
    initialTime = 0;
    elapsed = 0;
    update = function(elapsed) {
      if (initialTime === 0) {
        initialTime = elapsed;
      } else {
        if (elapsed - initialTime >= duration) {
          return obj[key] = endValue;
        } else {
          obj[key] = initialVal + (easeFunc(parseFloat((elapsed - initialTime) / duration)) * diff);
        }
      }
      return requestAnimationFrame(update);
    };
    return requestAnimationFrame(update);
  };

  (function() {
    var el, header, i, len, main, results, scrollToMains;
    scrollToMains = document.querySelectorAll('.scroll-to-main');
    header = document.getElementById('site-header');
    main = document.getElementById('site-content');
    results = [];
    for (i = 0, len = scrollToMains.length; i < len; i++) {
      el = scrollToMains[i];
      results.push(el.addEventListener('click', function() {
        var scrollTo;
        scrollTo = main.offsetTop;
        return animate(document.body, 'scrollTop', scrollTo, 500, easeInOut);
      }));
    }
    return results;
  })();

}).call(this);
