// Generated by CoffeeScript 1.12.4
(function() {
  var animateScrollToElement, animateValueOverTime, easeOutCubic, log;

  document.documentElement.classList.remove('no-js');

  log = function() {
    var args;
    if (typeof console === "undefined" || console === null) {
      return false;
    }
    args = [].slice.apply(arguments);
    return console.log.apply(console, args);
  };

  log('Thanks for checking out my site\'s theme\'s code!');

  log('The raw source is available on my GitHub at https://github.com/lytedev');

  easeOutCubic = function(t) {
    return (--t) * t * t + 1;
  };

  animateValueOverTime = function(initialValue, endValue, duration, callback, easeFunc) {
    var diff, elapsed, initialTime, update;
    if (typeof requestAnimationFrame === "undefined" || requestAnimationFrame === null) {
      return obj[key] = endValue;
    }
    if (easeFunc == null) {
      easeFunc = function(time) {
        return time;
      };
    }
    diff = parseFloat(endValue) - parseFloat(initialValue);
    initialTime = 0;
    elapsed = 0;
    update = function(elapsed) {
      if (initialTime === 0) {
        initialTime = elapsed;
      } else {
        if (elapsed - initialTime >= duration) {
          return callback(endValue);
        } else {
          callback(initialValue + (easeFunc(parseFloat((elapsed - initialTime) / duration)) * diff));
        }
      }
      return requestAnimationFrame(update);
    };
    return requestAnimationFrame(update);
  };

  animateScrollToElement = function(el) {
    var scroll, scrollTo, top;
    scrollTo = el.offsetTop;
    top = (window.pageYOffset || document.scrollTop) - (document.clientTop || 0) || 0;
    scroll = function(val) {
      return window.scroll(0, val);
    };
    return animateValueOverTime(top, scrollTo, 500, scroll, easeOutCubic);
  };

  (function() {
    var el, i, len, main, results, scrollToMainElements;
    scrollToMainElements = document.getElementsByClassName('scroll-to-main');
    main = document.getElementById('site-content');
    results = [];
    for (i = 0, len = scrollToMainElements.length; i < len; i++) {
      el = scrollToMainElements[i];
      results.push(el.addEventListener('click', function() {
        return animateScrollToElement(main);
      }));
    }
    return results;
  })();

}).call(this);
